[package]
name = "embassy-nxp-mkl82z7-examples"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[features]
default = ["time-driver-tpm"]
time-driver-tpm = ["embassy-nxp/time-driver-tpm", "embassy-time/tick-hz-1_000_000"]
time-driver-lptmr = ["embassy-nxp/time-driver-lptmr", "embassy-time/tick-hz-1_000"]

[dependencies]
cortex-m = { version = "0.7.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = "0.7.5"
cortex-m-semihosting = "0.5"
defmt = "1.0.1"
defmt-rtt = "1.0.0"
panic-probe = { version = "1.0.0", features = ["print-defmt"] }
embassy-nxp = { version = "0.1.0", path = "../../embassy-nxp", features = ["defmt", "mkl82z7", "unstable-pac", "time", "executor-thread"] }
embassy-executor = { version = "0.10.0", path = "../../embassy-executor", features = ["defmt"] }
embassy-time = { version = "0.5.1", path = "../../embassy-time", features = ["defmt"] }
embassy-hal-internal = { version = "0.5.0", path = "../../embassy-hal-internal" }
embassy-futures = { version = "0.1.2", path = "../../embassy-futures" }
heapless = "0.8"

[[bin]]
name = "low_power"
path = "src/bin/low_power.rs"
required-features = ["time-driver-tpm"]

[[bin]]
name = "lptmr_time"
path = "src/bin/lptmr_time.rs"
required-features = ["time-driver-lptmr"]

[profile.dev]
opt-level = 1
debug = 2

[profile.release]
debug = 2
lto = true
opt-level = "s"

[package.metadata.embassy]
build = [
  { target = "thumbv6m-none-eabi", artifact-dir = "out/examples/mkl82z7" }
]
